# Generated by Django 3.2.6 on 2021-09-02 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=40)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('profile_pic_url', models.URLField()),
                ('location', models.IntegerField()),
                ('password', models.CharField(max_length=500)),
                ('fully_set_up', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.IntegerField()),
                ('date', models.DateField()),
                ('forecast', models.TextField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plantapi.user')),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('plant_name', models.CharField(max_length=30)),
                ('plant_birthday', models.DateField()),
                ('last_watered', models.DateField()),
                ('last_trimmed', models.DateField()),
                ('last_repotted', models.DateField()),
                ('indoor', models.BooleanField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plantapi.user')),
            ],
        ),
    ]
