# Generated by Django 3.2.6 on 2021-08-21 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plants',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('plant_name', models.CharField(max_length=50)),
                ('plant_birthday', models.DateTimeField()),
                ('last_water', models.DateTimeField()),
                ('last_trim', models.DateTimeField()),
                ('last_repot', models.DateTimeField()),
                ('notes', models.TextField()),
                ('plant_pic', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('profile_pic_url', models.URLField()),
                ('location', models.IntegerField()),
                ('password', models.CharField(max_length=30)),
                ('fully_set_up', models.BooleanField()),
                ('private', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('forecast', models.TextField()),
            ],
        ),
    ]
